# Generated by Django 4.2 on 2025-10-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('profesor', models.CharField(max_length=100)),
                ('creditos', models.IntegerField(default=3)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='cursos', to='estudiantes.estudiante')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
