# Generated by Django 4.2 on 2025-10-24 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseZoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('duracion_minutos', models.IntegerField(default=60)),
                ('session_name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_vivo', 'En Vivo'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('url_grabacion', models.URLField(blank=True, null=True)),
                ('max_participantes', models.IntegerField(default=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_zoom', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Clase Zoom',
                'verbose_name_plural': 'Clases Zoom',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('asistio', models.BooleanField(default=False)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='cursos.clasezoom')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_asistidas', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'unique_together': {('clase', 'estudiante')},
            },
        ),
    ]
