# Generated by Django 4.2 on 2025-10-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseEnLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('url_clase', models.URLField(blank=True)),
                ('url_grabacion', models.URLField(blank=True)),
                ('fecha_clase', models.DateTimeField()),
                ('duracion_minutos', models.IntegerField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_vivo', 'En Vivo'), ('finalizada', 'Finalizada')], default='programada', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Clases en Línea',
                'ordering': ['-fecha_clase'],
            },
        ),
        migrations.CreateModel(
            name='ForoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foros', to='academico.claseenlinea')),
            ],
            options={
                'verbose_name_plural': 'Foros de Clase',
            },
        ),
        migrations.CreateModel(
            name='MensajeForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_foro', to='estudiantes.estudiante')),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='academico.foroclase')),
            ],
            options={
                'ordering': ['fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('creditos', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='cursos.curso')),
            ],
        ),
        migrations.AddField(
            model_name='claseenlinea',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='academico.materia'),
        ),
        migrations.CreateModel(
            name='ControlEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('periodo', models.CharField(max_length=50)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('cursando', 'Cursando'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('baja', 'Baja')], default='cursando', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_escolar', to='estudiantes.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia')),
            ],
            options={
                'verbose_name_plural': 'Control Escolar',
                'unique_together': {('estudiante', 'materia', 'periodo')},
            },
        ),
    ]
