# Generated by Django 4.2 on 2025-10-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=200)),
                ('foto', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.URLField(blank=True, null=True)),
                ('nivel_educativo', models.CharField(choices=[('preparatoria', 'Preparatoria'), ('tsu', 'Técnico Superior Universitario'), ('licenciatura', 'Carrera Profesional'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=20)),
                ('programa', models.CharField(max_length=200)),
                ('periodo_actual', models.CharField(max_length=50)),
                ('fecha_limite_actividades', models.DateField(blank=True, null=True)),
                ('progreso_academico', models.IntegerField(default=0)),
                ('materias_cursadas', models.IntegerField(default=0)),
                ('materias_totales', models.IntegerField(default=0)),
                ('promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='AsignacionTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='estudiantes.estudiante')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='perfiles.tutor')),
            ],
            options={
                'unique_together': {('estudiante', 'tutor')},
            },
        ),
    ]
