# Generated by Django 4.2 on 2025-10-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('url_recurso', models.URLField()),
                ('tipo_recurso', models.CharField(choices=[('libro', 'Libro'), ('revista', 'Revista'), ('articulo', 'Artículo'), ('video', 'Video')], max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Biblioteca Digital',
            },
        ),
        migrations.CreateModel(
            name='MesaAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('tecnico', 'Soporte Técnico'), ('academico', 'Académico'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('respuesta', models.TextField(blank=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name_plural': 'Mesa de Ayuda',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo_evento', models.CharField(choices=[('clase', 'Clase'), ('examen', 'Examen'), ('entrega', 'Entrega de Actividad'), ('evento', 'Evento Institucional')], max_length=50)),
                ('todos_estudiantes', models.BooleanField(default=False)),
                ('cursos', models.ManyToManyField(blank=True, related_name='eventos', to='cursos.curso')),
            ],
            options={
                'verbose_name_plural': 'Calendario',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CentroIdiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(choices=[('ingles', 'Inglés'), ('frances', 'Francés'), ('aleman', 'Alemán'), ('italiano', 'Italiano'), ('japones', 'Japonés'), ('mandarin', 'Mandarín')], max_length=20)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('duracion_semanas', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instructor', models.CharField(max_length=200)),
                ('cupo_maximo', models.IntegerField(default=25)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('estudiantes_inscritos', models.ManyToManyField(blank=True, related_name='cursos_idiomas', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name_plural': 'Centro de Idiomas',
            },
        ),
    ]
